language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t eugeniocaio10/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true eugeniocaio10/docker-react npm run test


deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-632193834611"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY